# Numpy

In [12]:
import numpy as np
import pandas as pd
from numpy import random

In [12]:
# declare a vector using a list as the argument
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [13]:
# declare a matrix using a nested list as the argument
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [15]:
# create an array with values that are spaced linearly in a specified interval
np.linspace(0, 10, 25) 

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [20]:
np.linspace(0,6,12)


array([0.        , 0.54545455, 1.09090909, 1.63636364, 2.18181818,
       2.72727273, 3.27272727, 3.81818182, 4.36363636, 4.90909091,
       5.45454545, 6.        ])

In [21]:
# arguments: start, stop, step
x = np.arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1.00000000e+00, 1.29154967e+01, 1.66810054e+02, 2.15443469e+03,
       2.78255940e+04, 3.59381366e+05, 4.64158883e+06, 5.99484250e+07,
       7.74263683e+08, 1.00000000e+10])

In [27]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)


array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                         [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [32]:
array_example.ndim # number of dimensions

3

In [34]:
array_example.size # number of elements

24

In [38]:
array_example.shape

(3, 2, 4)

## Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [40]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [43]:
b = a.reshape(2,3) # 2 righe e 3 colonne
print(b)

[[0 1 2]
 [3 4 5]]


## convert a 1D array into a 2D array


In [44]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [46]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [48]:
data = np.array([1, 2, 3,4])
data[1]


2

In [50]:
data[1:]


array([2, 3, 4])

In [51]:
data[0:2]


array([1, 2])

In [53]:
data[:2] # il terzo elemento non è incluso

array([1, 2])

In [56]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 7])


[1 2 3 4 5 6]


In [58]:
divisible_by_2 = a[a%2==0] 

In [59]:
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [61]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [70]:
x = np.arange(1, 25).reshape(2, 12) # 2 righe 12 colonne
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [66]:
np.hsplit(x, 3) # divido in 3 array della stessa dimensione

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [72]:
x = np.arange(1, 25).reshape(2, 12)
x.sum()

300

In [73]:
x.sum(axis=1) # somma le colonne

array([ 78, 222])

In [74]:
x.sum(axis=0) # somma le righe

array([14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36])

In [75]:
x * 2

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]])

In [78]:
x.max()

24

## 

## Generating random numbers

In [13]:
random.rand(5,5)

array([[0.82873304, 0.83732947, 0.93995321, 0.4824587 , 0.035169  ],
       [0.73931192, 0.41633162, 0.02532405, 0.84022989, 0.36435629],
       [0.40981843, 0.56302744, 0.0312408 , 0.73243457, 0.66338603],
       [0.9733696 , 0.81909976, 0.99743562, 0.43213313, 0.8363298 ],
       [0.81898836, 0.61414771, 0.38033897, 0.8800997 , 0.44244944]])

In [15]:
# normal distribution
random.randn(5,5)

array([[-0.22856584, -0.46868957,  1.19462405,  0.12012803,  2.21076571],
       [-0.30288091,  0.24951478,  1.92648171,  0.98574038,  0.17978887],
       [-1.91366223,  0.2958501 , -0.32314234,  0.19213856,  0.50466013],
       [ 1.105957  , -2.1553895 ,  1.21837897, -0.14653313,  0.28967928],
       [-0.82937108, -0.32664069, -1.72077898, -0.4375031 ,  0.50568969]])

In [18]:
v1 = np.arange(0, 5)
v1

array([0, 1, 2, 3, 4])

In [20]:
v1 * v1

array([ 0,  1,  4,  9, 16])

In [24]:
np.dot(v1,v1) # Dot product of two arrays

30

* If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).
* If both a and b are 2-D arrays, it is matrix multiplication a @ b

In [29]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [30]:
np.dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [31]:
np.dot(A,A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

## Statistics 

In [38]:
a = random.rand(10,3)
a

array([[0.19187418, 0.87582559, 0.56162781],
       [0.51230664, 0.20666619, 0.84515205],
       [0.23291618, 0.09504618, 0.23270536],
       [0.78750289, 0.04848794, 0.94972313],
       [0.9205708 , 0.69316814, 0.31305095],
       [0.36986148, 0.97549733, 0.66453958],
       [0.3607586 , 0.14217038, 0.19649627],
       [0.31940962, 0.98303469, 0.85305667],
       [0.92394525, 0.62759609, 0.56042174],
       [0.92868252, 0.0813924 , 0.20190055]])

In [39]:
np.mean(a)

0.521846239204111

In [40]:
np.std(a)

0.31746063988339907

In [41]:
np.trace(a)

0.6312457244996237